### PR TITLE
Charter proposal. Fixes #3

### LINKED ISSUE #3: Proposed PATWG Charter
Slightly late, but as promised, here is a proposed PATWG charter.

https://docs.google.com/document/d/13H-4If0ri2KDzonib0g9ZL3Oh2X3qo6DRiayYP8vsQE/edit?usp=sharing

### PR DESCRIPTION
**Pull request by ekr**
Charter transcribed from Google doc.

There were a number of comments in the Google doc that are not  addressed here. I propose to merge this PR into the repo and then create issues for those comments.

### CODE REVIEW

**Comment by ekr** [comment]
@seanturner @aramzs -- assuming you think this faithfully reflects the gdoc, please merge and I'll create issues for the comments.

**Comment by jwrosewell** [comment]
Why restrict the group to "new web platform features intended to be implemented in browsers or similar user agents"? This both limits the participants that can implement the standard(s) the group will ultimately produce in favor or browser vendors, and limits the possibility for innovation that might occur without such a constraint.

**Comment by ekr** [comment]
As I said previously, I am aware of this comment, but I didn't believe that it was sufficiently uncontroversial to merge into the gdoc prior to preparing this PR. As stated above, my intent was to merge this PR and then create separate issues for each of the unresolved comments in the gdoc.

**Comment by ekr** [comment]
@jwrosewell I believe I am done now. I tried to glue together some of your comments that I thought were related. Feel free to update/clarify/make PRs, etc.

**Pull request merged**
