### PR TITLE
Deweaponize 'all known'

### PR DESCRIPTION
**Pull request by martinthomson**

### CODE REVIEW

**Review by seanturner — APPROVED** [review]

**Comment by npdoty** [comment]
"all known" is in the charter template, fwiw.

I agree that it should generally be improved in the template, for example to include mitigations and not just documentation of implications. I don't know that removing "all known" is very important, though. It doesn't take that much text to refer to implications, and it's the ones known by the WG that must be documented.

**Comment by chrisn** [comment]
What's the purpose in removing "all known"? It opens the door to the WG choosing not to document vulnerabilities that it knows about, which would be an undesirable outcome.

**Comment by seanturner** [comment]
@chrisn I suggested removing it because I think it could also go the other way and a proposal could be held hostage - I know x but you don't.  Mind you, I would like to think this is pretty far fetched just like I think it's pretty far fetched that not having those words gives us an out to quietly, or otherwise, neglect to document security/privacy considerations. Given the participants, I would very much suspect that purposely omitting a known security/privacy considerations would sit well. And, I tend to think less is more here.

**Comment by chrisn** [comment]
I assume you mean "wouldn't sit well"? I agree, and would prefer not to see a change to the charter to allow for a situation that you describe as far-fetched.

**Comment by chrisn** [comment]
I'm surprised to see this merged where there's a clear absence of consensus, and no attempt made to resolve.

**Comment by AramZS** [comment]
@chrisn We did do a wider consensus call on the teleconference on this topic and found consensus after discussion there. See: https://github.com/patcg/meetings/blob/main/2023/05/02-telecon/README.md#review-wg-charter-prs

**Comment by chrisn** [comment]
Consensus should extend beyond those able to make specific teleconferences.

**Comment by martinthomson** [comment]
So this could be used to *force* the WG to document ridiculous vulnerabilities.  I don't see why you couldn't use another basis to object to a document that failed to capture vulnerabilities you thought important.

**Comment by AramZS** [comment]
@chrisn Our mission and scope text makes it very clear that we intend to review and document security and privacy concerns extensively. There is nothing stopping either internal reviewers in the group or the extensive horizontal review process within the W3C from rejecting a draft on the basis of privacy problems. Our concern, as has been stated by other folks on this thread, is that "all" presents a high potential for disruption.

**Comment by martinthomson** [comment]
no

**Pull request merged**
